### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by test2a** [lullius/pylibby#10]
tried to install this on my ubuntu install,

first found urllib3 error which i installed using pip3. fine. 
then in got "MutableMapping" same so i installed that one too and now there is a different issue

````
 pipenv install
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 33, in <module>
    sys.exit(load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')())
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 347, in install
    from .import core
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 21, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/__init__.py", line 65, in <module>
    from . import utils
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_pipenv.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 33, in <module>
    sys.exit(load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')())
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 347, in install
    from .import core
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 21, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/__init__.py", line 65, in <module>
    from . import utils
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
````

i am not so great at python so  any help would be greatly appreciated

**Comment by test2a** [comment]
ok. so i manually installed the requements and ignored pipenv and got it working. why don't we have a requirements.txt file?

**Comment by lullius** [comment]
A Pipfile is like a requirements.txt for pipenv. There's no need to manually install any Python packages when you use the Pipfile.

The reason you get `AttributeError: module 'collections' has no attribute 'MutableMapping'` is that your pipenv install is too old. Please have a look [here](https://github.com/pypa/pipenv/issues/5469).

**Comment by test2a** [comment]
@lullius what version of pipenv should i get?

```
pip install pipenv
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pipenv in /usr/lib/python3/dist-packages (11.9.0)
```

**Comment by lullius** [comment]
You need `-U` or `--upgrade` to upgrade a package using pip.

`pip install -U pipenv` should do it.

**Comment by test2a** [comment]
@lullius alright.

that did work but i am occasionally seeing connection issues. is that normal?

**Comment by lullius** [comment]
No, I haven't seen anything like that. I don't know what could cause it. Are you sure it's related to the software and not your network? If it stops working for no apparent reason maybe you could have a weak wifi signal?

Have you tried running it on another device, and if so, do you have the same connection issues on that device as well?

**Comment by test2a** [comment]
@lullius i don't have another machine so i am stuck with this....
what i see is, it happens 1-2 times, then the link works. then next time the same drill..

i downloaded 2 books  which once started did complete fully so that is not the trouble. Besides, i've been using libby/overdrive for past 3 years now so using those media i never had any trouble. it is still a much better proposition so i can live with that....

would it be possible to increase the timeout?

**Comment by lullius** [comment]
@ping made it possible to increase the timeout. Would you mind trying again with the new --timeout option?

**Comment by test2a** [comment]
@lullius this is nice. --retry 4 and i am not seeing crashes. this should be included in the readme because i suspect a lot of people would be having this trouble

**Comment by lullius** [comment]
Thanks for testing it out. I've updated the readme.
