### ISSUE TITLE
Experimenting with -dla ...

### ISSUE THREAD

**Issue by wtanksleyjr** [lullius/pylibby#25]
I'm curious whether the `-dla` option might work for me; it looks about right, but I can't make it work even when using the same basic command setup as a working -dl.

I ran a bunch of downloads just to get things working, of the form:

`pipenv run python pylibby.py -dl 206172 -f audiobook-mp3 -opf -e -ofs ~/dl/newodms/"%o/"`

So I tried the obvious command, and got a huge traceback. I can confirm I get the same traceback when I try downloading just that one single libby-ID listed before the traceback, so it's genuinely bad data in there. I'll report what I have, and then try returning that item because I already got it through other means, but I wonder: in general, is there a way to run a `-dla` but ignoring a list of specific items, or even marking all the current items downloaded? I'd like to use `-dla` from now on, but I don't need to catch up with everything I have now, only the new stuff.

`pipenv run python pylibby.py -dla audiobook-mp3 -opf -e -ofs ~/dl/newodms/"%o/"`

Specifically:

```
Downloading all loans with format audiobook-mp3
Loaded archive ./config/archive.json
114614/
Traceback (most recent call last):
  File "/home/william/pylibby/pylibby.py", line 1720, in <module>
    main()
  File "/home/william/pylibby/pylibby.py", line 1618, in main
    L.download_loan(
  File "/home/william/pylibby/pylibby.py", line 1060, in download_loan
    self.download_audiobook_mp3(
  File "/home/william/pylibby/pylibby.py", line 904, in download_audiobook_mp3
    tocout = get_toc_from_audiobook_info(audiobook_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/william/pylibby/pylibby.py", line 309, in get_toc_from_audiobook_info
    parsed_toc = parse_toc(audiobook_info["openbook"]["nav"]["toc"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/william/pylibby/pylibby.py", line 287, in parse_toc
    entries.append(parse_part_path(item["title"], content["path"]))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/william/pylibby/pylibby.py", line 269, in parse_part_path
    raise ValueError(f"Unexpected path format: {part_path}")
ValueError: Unexpected path format: {31984D68-AD8F-4EF1-B00C-4A595BADE0D1}Fmt425-Part01.mp3#275.253
```

**Comment by lullius** [comment]
Thanks for the feedback.

That book seems to have chapter markers with timestamps that are not integers. I've never seen that before. I just pushed 80694864c65a79c18fa5872916bb45d31cb4b7af which should fix the issue. If you could try again with the new code that would be great.

About -dla and downloading specific items: that is what the archive is for. If you left it as default it should be in config/archive.json. Inside there you should see a list of all the things you've downloaded. Everything inside archive.json is ignored when you run pylibby with -dla so that you won't keep downloading the same books over and over.

If you want to ignore a book for some reason you can add it to the archive and mark it as finished with "Finished: true". That will fool pylibby, making it skip that title. You shouldn't need anything other than the id of the book. Something like this:

```json
{
    "114614": {"Finished": true}
}
```

**Comment by wtanksleyjr** [comment]
Fantastic, that will work very well.

Yes, I can confirm that book now downloads. Thank you!!

-Wm
